name: Kevin Suttle
tagline: Designer. Developer. Writer. Presenter.
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: [true]
permalink: /posts/:title
exclude: ["CNAME", "README.md", "viewports.html"]
url: KevinSuttle.com