name: Kevin Suttle
tagline: Designer. Developer. Writer. Presenter.
highlighter: pygments
markdown: kramdown
permalink: /posts/:title
exclude: ["CNAME", "README.md", "/node_modules", "gulpfile.js", "package.json"]
url: KevinSuttle.com

destination: _site
