name: Kevin Suttle
tagline: Designer. Developer. Writer. Presenter.
pygments: [true]
markdown: redcarpet
permalink: /posts/:title
exclude: ["CNAME", "README.md", "/node_modules", "sass"]
url: KevinSuttle.com

source: src/
destination: dist/