name: Kevin Suttle
tagline: Designer. Developer. Writer. Presenter.
pygments: [true]
markdown: redcarpet
permalink: /posts/:title
exclude: ["CNAME", "README.md", "/node_modules"]
url: KevinSuttle.com

destination: _site