name: Kevin Suttle
tagline: Designer. Developer. Writer. Presenter.
highlighter: pygments
markdown: kramdown
kramdown:
    input: GFM
permalink: /posts/:title
exclude: ["CNAME", "README.md", "node_modules", "gulpfile.js", "package.json", "config.codekit"]
url: KevinSuttle.com
