name: Kevin Suttle
tagline: Product Designer. UX. UI. IA.
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: [true]
permalink: /posts/:title
exclude: ["CNAME", "README.md"]
url: KevinSuttle.com